### ISSUE TITLE
Display newly registered users in manager preview

### ISSUE THREAD

**Issue by dangho1** [fabianhaglund/sysdes-speed-dater#31]
https://blog.logrocket.com/the-complete-guide-to-using-localstorage-in-javascript-apps-ba44edb53a36/

maybe use key() to loop and get all keys, save them in an array and use getItem() with acquired keys
key for new users = name of user
value for new users = [name, email, number, age, gender, interests, password, profile image path]

**Comment by fabianhaglund** [comment]
`addToUsersSignup` merged to master

great work @dangho1
